import Head from "next/head";
import Image from "next/image";
import GlobalContainer from "../components/layouts/GlobalContainer";
import Navbar from "../components/layouts/NavBar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <GlobalContainer>
          <Navbar />
          <div className="container mx-auto px-4">
            <h1 className="text-3xl font-bold underline">
              {" "}
              hello there, I'm mia, currently studying computer science and
              design{" "}
              <a href="https://www.cmu.edu/interdisciplinary/programs/bcsa.html">
                at carnegie mellon with a interest in computer graphics.
              </a>
            </h1>
          </div>
        </GlobalContainer>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}
